more cleanup of installation scripts

diff --git a/software/Makefile b/software/Makefile
--- a/software/Makefile
+++ b/software/Makefile
@@ -1,5 +1,6 @@
 include ./.env
 export
+
 OS_IMG_NAME:=$(shell date "+%Y-%m-%d")_sticky_pi_${SPI_ARCH}.img
 PYTHON_RESOURCES := $(shell find src -name \*.py -print)
 .PHONY: base_os custom_os device_tree
@@ -15,38 +16,43 @@ net_conf: ${NET_CONF}
 python_package: ${PYTHON_PACKAGE}
 
 
-${BASE_OS_IMG_NAME}: utils/make_base_os.sh  utils/customize_os.sh os_stub ${DT_BLOB}
-	set +a
-	bash $< || rm -f tmp-${OS_IMG_NAME}
-	set -a
-	echo Made base image $@
+${BASE_OS_IMG_NAME}: utils/make_base_os.sh
+	@set +a
+	bash $< || (rm -f tmp-${OS_IMG_NAME}; echo "Failed to make base image!"; exit 1)
+	@echo "Made base image $@ !"
+	@set -a
+
 
 ${DT_BLOB}: utils/dt-blob.dts
-	dtc -I dts -O dtb $< -o $@
+	@dtc -I dts -O dtb $< -o $@ 2> /dev/null
+	@echo Made $@
 
 ${PYTHON_PACKAGE}: ${PYTHON_RESOURCES}
 	cd src && rm -r dist && python setup.py sdist
 	cp src/dist/*.tar.gz $@ -v
+	@echo Made $@
 
 ${NET_CONF}: .env
-	mkdir -p $(shell dirname $@)
-	echo "Interface=wlan0" > $@
-	echo "Connection=wireless" >>  $@
-	echo "Security=wpa"  >> $@
-	echo "IP=dhcp"  >> $@
-	echo "ESSID='$SPI_WIFI_SSID'"  >> $@
-	echo "Key='$SPI_WIFI_PASSWORD'" >> $@
+	@mkdir -p $(shell dirname $@)
+	@echo "Interface=wlan0" > $@
+	@echo "Connection=wireless" >>  $@
+	@echo "Security=wpa"  >> $@
+	@echo "IP=dhcp"  >> $@
+	@echo "ESSID='$SPI_WIFI_SSID'"  >> $@
+	@echo "Key='$SPI_WIFI_PASSWORD'" >> $@
+	@echo Made $@
 
-spi-${OS_IMG_NAME}: utils/emulate_arm.sh  base-${OS_IMG_NAME} ${PYTHON_PACKAGE} ${NET_CONF}
-	set +a
-	bash $< || rm -f tmp-${OS_IMG_NAME}
-	echo Made final image $@ !
-	set -a
+spi-${OS_IMG_NAME}: utils/emulate_arm.sh  base-${OS_IMG_NAME} ${PYTHON_PACKAGE} ${NET_CONF}  ${DT_BLOB}
+	@set +a
+	bash $< || (rm -f tmp-${OS_IMG_NAME};  echo "Failed to make final image!"; exit 1)
+	@echo "Made final image $@!"
+	@set -a
+
 
 
 clean:
-	rm tmp-*.img -f
+	rm tmp-*.img -f ${NET_CONF} ${DT_BLOB} ${PYTHON_PACKAGE}
 	losetup --detach-all
 
 cleanall: clean
-	rm base-*.img custom-*.img custom-*.ro -f
+	rm base-*.img spi-*.img  -f
